sources:
  - MAXExample/Sources
templates:
  - tools/sourcery/templates
output:
  MAXExampleTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - MAXExample
  autoMockableImports:
    - RxSwift
    - RxCocoa
